PIP_NOT_FOUND = 1
TEST_FOLDERS_NOT_FOUND = 2
RESULT_DICT_EMPTY = 3
COVERAGE_MATRIX_EMPTY = 4
#EXCEL_REPORT_FILE_NOT_FOUND = 7
JSON_REPORT_FILE_NOT_FOUND = 7
FAILED_WRITE_PROJECT_COVERAGE_RC_FILE = 15
FAILED_COPY_COVERAGE_RC_FILE = 8
